# Generated by Django 3.2.6 on 2021-08-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('secretIdentity', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squadName', models.CharField(max_length=150, verbose_name='Nomi')),
                ('homeTown', models.CharField(max_length=150, verbose_name='Nomi')),
                ('formed', models.IntegerField()),
                ('secretBase', models.CharField(max_length=150, verbose_name='Nomi')),
                ('active', models.BooleanField(default=True)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.members')),
            ],
        ),
    ]
