# Generated by Django 3.2.6 on 2021-08-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210821_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_members', to='api.members'),
        ),
    ]
