# Generated by Django 3.2.6 on 2021-08-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_squad_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='power',
            field=models.ManyToManyField(to='api.Power'),
        ),
    ]
