# Generated by Django 3.2.6 on 2021-08-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210821_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='power',
            new_name='powers',
        ),
    ]
